spring:
  application:
    name: daoujapan

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: MYSQL
    generate-ddl: false
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:23306/test_database?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: daoujapan
    password: daou1234!
  security:
    user:
      password: 1234

  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat

  whitelist:
    ip-list:
      - 1.2.3.4
      - 127.0.0.1
      - 0:0:0:0:0:0:0:1

springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

schedule-file:
  job:
    file-saver-run: 0 0 0 * * *
  extensions:
    - txt
    - csv

error:
  message:
    time-required: 조회하시려는 날짜를 입력해주세요.
    from-is-not-after-to: 조회 시작날짜는 조회 종료날짜보다 먼저 올 수 없습니다.

server:
  servlet:
    encoding:
      charset: UTF-8
